## Import Libraries

In [1]:
import numpy as np
import pandas as pd
import os

## Import Datasets

In [2]:
## Import Orders Products Merged
df_ords_prods_merge=pd.read_pickle(r'/Users/sportsfan922/Documents/InstacartBasketAnalysis1025/Prepared Data/orders_products_merged.pkl')

In [3]:
## First Million Rows from Orders and Products Merged Dataset
df=df_ords_prods_merge[:1000000]

## User Defined Function: Product Range Types

In [4]:
def price_label(row):
    if row['prices']<=5:
        return 'Low Range Product'
    elif row['prices']>5 and row['prices']<=15:
        return 'Mid Range Product'
    elif row['prices']>15:
        return'High Range Product'
    else: return 'Not enough data'

## Apply User Defined Function

In [5]:
df['price_range'] = df.apply(price_label, axis=1)

/var/folders/3m/qtt2ngkx7fsblysy8c_rhytr0000gp/T/ipykernel_8439/2848743372.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_range'] = df.apply(price_label, axis=1)

In [6]:
df_ords_prods_merge['price_range'] = df_ords_prods_merge.apply(price_label, axis=1)

In [7]:
## Check the Value Counts
df['price_range'].value_counts()

price_range
Mid Range Product    756450
Low Range Product    243550
Name: count, dtype: int64

In [8]:
## Check the Maximum Price Value
df['prices'].max()

14.8

In [9]:
df_ords_prods_merge['price_range'].value_counts()

price_range
Mid Range Product     21889009
Low Range Product     10126339
High Range Product      417682
Name: count, dtype: int64

## Check Headings

In [10]:
df.head()

,Unnamed: 0_x,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,_merge,price_range
0,0,2539329,1,1,2,8,NaN,196,1,0,195,Soda,77,7,9.0,both,Mid Range Product
1,1,2398795,1,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product
2,2,473747,1,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product
3,3,2254736,1,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product
4,4,431534,1,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product

## Drop Columns Not Needed

In [11]:
df.drop(columns=['Unnamed: 0_x','Unnamed: 0_y','_merge'], inplace=True)

/var/folders/3m/qtt2ngkx7fsblysy8c_rhytr0000gp/T/ipykernel_8439/285460417.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['Unnamed: 0_x','Unnamed: 0_y','_merge'], inplace=True)

In [12]:
df.head(20)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid Range Product
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid Range Product
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid Range Product
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid Range Product
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid Range Product
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,Mid Range Product
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,Mid Range Product
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,Mid Range Product
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,Mid Range Product
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,Mid Range Product
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,Mid Range Product
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,Mid Range Product
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,Mid Range Product
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,Mid Range Product
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,Mid Range Product
15,2293453,19,2,5,14,6.0,196,3,0,Soda,77,7,9.0,Mid Range Product
16,1973799,19,5,6,12,8.0,196,15,1,Soda,77,7,9.0,Mid Range Product
17,532817,19,7,4,17,6.0,196,1,1,Soda,77,7,9.0,Mid Range Product
18,1573906,21,10,3,10,6.0,196,2,0,Soda,77,7,9.0,Mid Range Product
19,1593000,31,10,3,8,7.0,196,17,0,Soda,77,7,9.0,Mid Range Product

## If Statements with LOC Function

In [13]:
## High Range Product
df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'
df.loc[(df['prices'] <= 15) & (df['prices'] > 5), 'price_range_loc'] = 'Mid-range product' 
df.loc[df['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

/var/folders/3m/qtt2ngkx7fsblysy8c_rhytr0000gp/T/ipykernel_8439/150985519.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'

## For Loops

In [14]:
for x in range(30,45):
    print("My age is %d" %(x))

My age is 30
My age is 31
My age is 32
My age is 33
My age is 34
My age is 35
My age is 36
My age is 37
My age is 38
My age is 39
My age is 40
My age is 41
My age is 42
My age is 43
My age is 44

In [15]:
df_ords_prods_merge['order_dow'].value_counts(dropna=False)

order_dow
0    6209410
1    5665604
6    4500101
2    4217610
5    4209334
3    3843929
4    3787042
Name: count, dtype: int64

In [16]:
## For Loop For Busiest Day
result = []

for value in df_ords_prods_merge["order_dow"]:
  if value == 0:
    result.append("Busiest day")
  elif value == 4:
    result.append("Least busy")
  else:
    result.append("Regularly busy")

In [17]:
result

['Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 ...]

## Add New Column For Busiest Day

In [18]:
df_ords_prods_merge['busiest_day']=result

In [19]:
df_ords_prods_merge['busiest_day'].value_counts(dropna=False)

busiest_day
Regularly busy    22436578
Busiest day        6209410
Least busy         3787042
Name: count, dtype: int64

## New For Loop: Busiest Days and Least Busiest Days

In [20]:
## For Loop For Busiest Day
result=[]

for value in df_ords_prods_merge["order_dow"]:
  if value in (0,1):
    result.append("Busiest days")
  elif value in (3,4):
    result.append("Least busy days")
  else:
    result.append("Regularly busy")

## Add Column Busiest and Least Busiest Days

In [21]:
df_ords_prods_merge['2busiest_slowest_days']=result

In [22]:
## 2 Busiest and 2 Slowest Days of the Week
df_ords_prods_merge['2busiest_slowest_days'].value_counts(dropna=False)

2busiest_slowest_days
Regularly busy     12927045
Busiest days       11875014
Least busy days     7630971
Name: count, dtype: int64

In [23]:
## Check headings for New Columns 
df_ords_prods_merge.head()

,Unnamed: 0_x,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,_merge,price_range,busiest_day,2busiest_slowest_days
0,0,2539329,1,1,2,8,NaN,196,1,0,195,Soda,77,7,9.0,both,Mid Range Product,Regularly busy,Regularly busy
1,1,2398795,1,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product,Regularly busy,Least busy days
2,2,473747,1,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product,Regularly busy,Least busy days
3,3,2254736,1,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product,Least busy,Least busy days
4,4,431534,1,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product,Least busy,Least busy days

This dataset looks good to go!

## What are the Busiest and Least Busy Hours of the Day?

In [24]:
## Hours of the Day Value Counts
df_ords_prods_merge['order_hour_of_day'].value_counts().sort_values(ascending=False)

order_hour_of_day
10    2764288
11    2738483
14    2691448
15    2664420
13    2663169
12    2620719
16    2537358
9     2456591
17    2089385
8     1719888
18    1637858
19    1259335
20     976991
7      891900
21     796341
22     634715
23     402593
6      290763
0      218925
1      115780
5       88054
2       69429
4       53280
3       51317
Name: count, dtype: int64

## Busiest Periods of the Day

In [25]:
## Busiest Periods of the Day
result=[]
for value in df_ords_prods_merge['order_hour_of_day']:
    if value in (10,11,14,15,13,12,16,9):
        result.append('Most Orders')
    elif value in (17,8,18,19,20,7,21,22):
        result.append("Average Orders")
    else:
        result.append("Fewest Orders")

In [26]:
df_ords_prods_merge['Busiest_Period_Of_Day']=result

In [27]:
## Busiest Periods of the Day Value Counts
df_ords_prods_merge['Busiest_Period_Of_Day'].value_counts(dropna=False)

Busiest_Period_Of_Day
Most Orders       21136476
Average Orders    10006413
Fewest Orders      1290141
Name: count, dtype: int64

In [28]:
## Check Headers
df_ords_prods_merge.head(10)

,Unnamed: 0_x,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,_merge,price_range,busiest_day,2busiest_slowest_days,Busiest_Period_Of_Day
0,0,2539329,1,1,2,8,NaN,196,1,0,195,Soda,77,7,9.0,both,Mid Range Product,Regularly busy,Regularly busy,Average Orders
1,1,2398795,1,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product,Regularly busy,Least busy days,Average Orders
2,2,473747,1,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product,Regularly busy,Least busy days,Most Orders
3,3,2254736,1,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product,Least busy,Least busy days,Average Orders
4,4,431534,1,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product,Least busy,Least busy days,Most Orders
5,5,3367565,1,6,2,7,19.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product,Regularly busy,Regularly busy,Average Orders
6,6,550135,1,7,1,9,20.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product,Regularly busy,Busiest days,Most Orders
7,7,3108588,1,8,1,14,14.0,196,2,1,195,Soda,77,7,9.0,both,Mid Range Product,Regularly busy,Busiest days,Most Orders
8,8,2295261,1,9,1,16,0.0,196,4,1,195,Soda,77,7,9.0,both,Mid Range Product,Regularly busy,Busiest days,Most Orders
9,9,2550362,1,10,4,8,30.0,196,1,1,195,Soda,77,7,9.0,both,Mid Range Product,Least busy,Least busy days,Average Orders

In [29]:
## Remove Not Needed Columns
df_ords_prods_merge.drop(columns=['_merge'], inplace=True)

In [30]:
## Check Headings 
df_ords_prods_merge.head(10)

,Unnamed: 0_x,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,price_range,busiest_day,2busiest_slowest_days,Busiest_Period_Of_Day
0,0,2539329,1,1,2,8,NaN,196,1,0,195,Soda,77,7,9.0,Mid Range Product,Regularly busy,Regularly busy,Average Orders
1,1,2398795,1,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,Mid Range Product,Regularly busy,Least busy days,Average Orders
2,2,473747,1,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,Mid Range Product,Regularly busy,Least busy days,Most Orders
3,3,2254736,1,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,Mid Range Product,Least busy,Least busy days,Average Orders
4,4,431534,1,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,Mid Range Product,Least busy,Least busy days,Most Orders
5,5,3367565,1,6,2,7,19.0,196,1,1,195,Soda,77,7,9.0,Mid Range Product,Regularly busy,Regularly busy,Average Orders
6,6,550135,1,7,1,9,20.0,196,1,1,195,Soda,77,7,9.0,Mid Range Product,Regularly busy,Busiest days,Most Orders
7,7,3108588,1,8,1,14,14.0,196,2,1,195,Soda,77,7,9.0,Mid Range Product,Regularly busy,Busiest days,Most Orders
8,8,2295261,1,9,1,16,0.0,196,4,1,195,Soda,77,7,9.0,Mid Range Product,Regularly busy,Busiest days,Most Orders
9,9,2550362,1,10,4,8,30.0,196,1,1,195,Soda,77,7,9.0,Mid Range Product,Least busy,Least busy days,Average Orders

## Export File to Prepared Data Folder

In [31]:
df_ords_prods_merge.to_pickle('/Users/sportsfan922/Documents/InstacartBasketAnalysis1025/Prepared Data/df_ords_prods_merge_cust_col.pkl')